// This file is auto-generated by @hey-api/openapi-ts
import { type Options, createClient, createConfig } from '@hey-api/client-fetch'

import type {
  GetExceptionClassData,
  GetExceptionClassError,
  GetExceptionClassResponse,
  GetGene2TranscriptsClassData,
  GetGene2TranscriptsClassError,
  GetGene2TranscriptsClassResponse,
  GetGene2TranscriptsV2ClassData,
  GetGene2TranscriptsV2ClassError,
  GetGene2TranscriptsV2ClassResponse,
  GetHelloClassData,
  GetHelloClassError,
  GetHelloClassResponse,
  GetHgvs2ReferenceClassData,
  GetHgvs2ReferenceClassError,
  GetHgvs2ReferenceClassResponse,
  GetLimitedRateHellloData,
  GetLimitedRateHellloError,
  GetLimitedRateHellloResponse,
  GetLovdClassData,
  GetLovdClassError,
  GetLovdClassResponse,
  GetVariantFormatterClassData,
  GetVariantFormatterClassError,
  GetVariantFormatterClassResponse,
  GetVariantValidatorClassData,
  GetVariantValidatorClassError,
  GetVariantValidatorClassResponse,
  GetVariantValidatorEnsemblClassData,
  GetVariantValidatorEnsemblClassError,
  GetVariantValidatorEnsemblClassResponse
} from './types.gen'

export const client = createClient(createConfig())

/**
 * This endpoint has a rate limit of 4 requests per second.
 */
export const getLovdClass = <ThrowOnError extends boolean = false>(
  options: Options<GetLovdClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetLovdClassResponse, GetLovdClassError, ThrowOnError>({
    ...options,
    url: '/LOVD/lovd/{genome_build}/{variant_description}/{transcript_model}/{select_transcripts}/{checkonly}/{liftover}'
  })
}

/**
 * This endpoint has a rate limit of 4 requests per second.
 */
export const getVariantFormatterClass = <ThrowOnError extends boolean = false>(
  options: Options<GetVariantFormatterClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetVariantFormatterClassResponse,
    GetVariantFormatterClassError,
    ThrowOnError
  >({
    ...options,
    url: '/VariantFormatter/variantformatter/{genome_build}/{variant_description}/{transcript_model}/{select_transcripts}/{checkonly}'
  })
}

/**
 * This endpoint has a rate limit of 1 request per second.
 */
export const getGene2TranscriptsClass = <ThrowOnError extends boolean = false>(
  options: Options<GetGene2TranscriptsClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetGene2TranscriptsClassResponse,
    GetGene2TranscriptsClassError,
    ThrowOnError
  >({
    ...options,
    url: '/VariantValidator/tools/gene2transcripts/{gene_query}'
  })
}

/**
 * This endpoint has a rate limit of 1 request per second.
 */
export const getGene2TranscriptsV2Class = <ThrowOnError extends boolean = false>(
  options: Options<GetGene2TranscriptsV2ClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetGene2TranscriptsV2ClassResponse,
    GetGene2TranscriptsV2ClassError,
    ThrowOnError
  >({
    ...options,
    url: '/VariantValidator/tools/gene2transcripts_v2/{gene_query}/{limit_transcripts}/{transcript_set}/{genome_build}'
  })
}

export const getHgvs2ReferenceClass = <ThrowOnError extends boolean = false>(
  options: Options<GetHgvs2ReferenceClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetHgvs2ReferenceClassResponse,
    GetHgvs2ReferenceClassError,
    ThrowOnError
  >({
    ...options,
    url: '/VariantValidator/tools/hgvs2reference/{hgvs_description}'
  })
}

/**
 * This endpoint has a rate limit of 2 requests per second.
 */
export const getVariantValidatorClass = <ThrowOnError extends boolean = false>(
  options: Options<GetVariantValidatorClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetVariantValidatorClassResponse,
    GetVariantValidatorClassError,
    ThrowOnError
  >({
    ...options,
    url: '/VariantValidator/variantvalidator/{genome_build}/{variant_description}/{select_transcripts}'
  })
}

/**
 * This endpoint has a rate limit of 2 requests per second.
 */
export const getVariantValidatorEnsemblClass = <ThrowOnError extends boolean = false>(
  options: Options<GetVariantValidatorEnsemblClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetVariantValidatorEnsemblClassResponse,
    GetVariantValidatorEnsemblClassError,
    ThrowOnError
  >({
    ...options,
    url: '/VariantValidator/variantvalidator_ensembl/{genome_build}/{variant_description}/{select_transcripts}'
  })
}

export const getHelloClass = <ThrowOnError extends boolean = false>(
  options?: Options<GetHelloClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetHelloClassResponse, GetHelloClassError, ThrowOnError>({
    ...options,
    url: '/hello/'
  })
}

export const getLimitedRateHelllo = <ThrowOnError extends boolean = false>(
  options?: Options<GetLimitedRateHellloData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetLimitedRateHellloResponse,
    GetLimitedRateHellloError,
    ThrowOnError
  >({
    ...options,
    url: '/hello/limit'
  })
}

export const getExceptionClass = <ThrowOnError extends boolean = false>(
  options: Options<GetExceptionClassData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetExceptionClassResponse,
    GetExceptionClassError,
    ThrowOnError
  >({
    ...options,
    url: '/hello/trigger_error/{error_code}'
  })
}
