// This file is auto-generated by @hey-api/openapi-ts
import { type Options, createClient, createConfig } from '@hey-api/client-fetch'

import type {
  GenesTranscriptsListData,
  GenesTranscriptsListError,
  GenesTranscriptsListResponse2,
  SeqvarsCsqData,
  SeqvarsCsqError,
  SeqvarsCsqResponse2,
  StrucvarsCsqData,
  StrucvarsCsqError,
  StrucvarsCsqResponse2,
  VersionsInfoError,
  VersionsInfoResponse2
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Query for transcripts of a gene.
 */
export const genesTranscriptsList = <ThrowOnError extends boolean = false>(
  options: Options<GenesTranscriptsListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GenesTranscriptsListResponse2,
    GenesTranscriptsListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/genes/transcripts'
  })
}

/**
 * Query for consequence of a variant.
 */
export const seqvarsCsq = <ThrowOnError extends boolean = false>(
  options: Options<SeqvarsCsqData, ThrowOnError>
) => {
  return (options?.client ?? client).get<SeqvarsCsqResponse2, SeqvarsCsqError, ThrowOnError>({
    ...options,
    url: '/api/v1/seqvars/csq'
  })
}

/**
 * Query for consequence of a variant.
 */
export const strucvarsCsq = <ThrowOnError extends boolean = false>(
  options: Options<StrucvarsCsqData, ThrowOnError>
) => {
  return (options?.client ?? client).get<StrucvarsCsqResponse2, StrucvarsCsqError, ThrowOnError>({
    ...options,
    url: '/api/v1/strucvars/csq'
  })
}

/**
 * Query for consequence of a variant.
 */
export const versionsInfo = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<VersionsInfoResponse2, VersionsInfoError, ThrowOnError>({
    ...options,
    url: '/api/v1/versionsInfo'
  })
}
