import { GenesGtexTissue, GenesGtexTissueDetailed } from "@/ext/annonars-api/src/lib"

export const TISSUE_LABELS: { [Key in GenesGtexTissue]: string } = {
 'AdiposeTissue' : 'Adipose Tissue',
 'AdrenalGland' : 'Adrenal Gland',
 'Bladder' : 'Bladder',
 'Blood' : 'Blood',
 'BloodVessel' : 'Blood Vessel',
 'BoneMarrow' : 'Bone Marrow',
 'Brain' : 'Brain',
 'Breast' : 'Breast',
 'CervixUteri' : 'Cervix Uteri',
 'Colon' : 'Colon',
 'Esophagus' : 'Esophagus',
 'FallopianTube' : 'Fallopian Tube',
 'Heart' : 'Heart',
 'Kidney' : 'Kidney',
 'Liver' : 'Liver',
 'Lung' : 'Lung',
 'Muscle' : 'Muscle',
 'Nerve' : 'Nerve',
 'Ovary' : 'Ovary',
 'Pancreas' : 'Pancreas',
 'Pituitary' : 'Pituitary',
 'Prostate' : 'Prostate',
 'SalivaryGland' : 'Salivary Gland',
 'Skin' : 'Skin',
 'SmallIntestine' : 'Small Intestine',
 'Spleen' : 'Spleen',
 'Stomach' : 'Stomach',
 'Testis' : 'Testis',
 'Thyroid' : 'Thyroid',
 'Uterus' : 'Uterus',
 'Vagina' : 'Vagina'
}

export const TISSUE_DETAILED_LABELS: { [Key in GenesGtexTissueDetailed]: string } = {
 'AdiposeSubcutaneous' : 'Adipose - Subcutaneous',
 'AdiposeVisceralOmentum' : 'Adipose - Visceral (Omentum)',
 'AdrenalGland' : 'Adrenal Gland',
 'ArteryAorta' : 'Artery - Aorta',
 'ArteryCoronary' : 'Artery - Coronary',
 'ArteryTibial' : 'Artery - Tibial',
 'Bladder' : 'Bladder',
 'BrainAmygdala' : 'Brain - Amygdala',
 'BrainAnteriorCingulateCortex' : 'Brain - Anterior cingulate cortex (BA24)',
 'BrainCaudateBasalGanglia' : 'Brain - Caudate (basal ganglia)',
 'BrainCerebellarHemisphere' : 'Brain - Cerebellar Hemisphere',
 'BrainCerebellum' : 'Brain - Cerebellum',
 'BrainCortex' : 'Brain - Cortex',
 'BrainFrontalCortex' : 'Brain - Frontal Cortex (BA9)',
 'BrainHippocampus' : 'Brain - Hippocampus',
 'BrainHypothalamus' : 'Brain - Hypothalamus',
 'BrainNucleusAccumbens' : 'Brain - Nucleus accumbens (basal ganglia)',
 'BrainPutamenBasalGanglia' : 'Brain - Putamen (basal ganglia)',
 'BrainSpinalCord' : 'Brain - Spinal cord (cervical c-1)',
 'BrainSubstantiaNigra' : 'Brain - Substantia nigra',
 'BreastMammaryTissue' : 'Breast - Mammary Tissue',
 'CellsCulturedFibroblasts' : 'Cells - Cultured fibroblasts',
 'CellsEbvTransformedLymphocytes' : 'Cells - EBV-transformed lymphocytes',
 'CellsLeukemiaCellLine' : 'Cells - Leukemia cell line (CML)',
 'CervixEctocervix' : 'Cervix - Ectocervix',
 'CervixEndocervix' : 'Cervix - Endocervix',
 'ColonSigmoid' : 'Colon - Sigmoid',
 'ColonTransverse' : 'Colon - Transverse',
 'EsophagusGastroesophagealJunction' : 'Esophagus - Gastroesophageal Junction',
 'EsophagusMucosa' : 'Esophagus - Mucosa',
 'EsophagusMuscularis' : 'Esophagus - Muscularis',
 'FallopianTube' : 'Fallopian Tube',
 'HeartAtrialAppendage' : 'Heart - Atrial Appendage',
 'HeartLeftVentricle' : 'Heart - Left Ventricle',
 'KidneyCortex' : 'Kidney - Cortex',
 'KidneyMedulla' : 'Kidney - Medulla',
 'Liver' : 'Liver',
 'Lung' : 'Lung',
 'MinorSalivaryGland' : 'Minor Salivary Gland',
 'MuscleSkeletal' : 'Muscle - Skeletal',
 'NerveTibial' : 'Nerve - Tibial',
 'Ovary' : 'Ovary',
 'Pancreas' : 'Pancreas',
 'Pituitary' : 'Pituitary',
 'Prostate' : 'Prostate',
 'SalivaryGland' : 'Salivary Gland',
 'SkinNotSunExposedSuprapubic' : 'Skin - Not Sun Exposed (Suprapubic)',
 'SkinSunExposedLowerLeg' : 'Skin - Sun Exposed (Lower leg)',
 'SmallIntestineTerminalIleum' : 'Small Intestine - Terminal Ileum',
 'Spleen' : 'Spleen',
 'Stomach' : 'Stomach',
 'Testis' : 'Testis',
 'Thyroid' : 'Thyroid',
 'Uterus' : 'Uterus',
 'Vagina' : 'Vagina',
 'WholeBlood' : 'Whole Blood'
}
