// This file is auto-generated by @hey-api/openapi-ts

export type PublicationsExportBiocjsonResponse = {
  PubTator3: Array<PublicationsExportBiocjsonResponseEntry>
}

export type PublicationsExportBiocjsonResponseEntry = {
  _id: string
  id: string
  passages: Array<PublicationsExportBiocjsonResponseEntryPassage>
  pmid: number
  pmcid?: string
  date: string
  journal: string
  authors: Array<string>
  [key: string]: unknown | string | PublicationsExportBiocjsonResponseEntryPassage | number
}

export type PublicationsExportBiocjsonResponseEntryPassage = {
  infons?: PublicationsExportBiocjsonResponseEntryPassageInfons
  offset?: number
  text?: string
  annotations?: Array<PublicationsExportBiocjsonResponseEntryPassageAnnotation>
  [key: string]:
    | unknown
    | PublicationsExportBiocjsonResponseEntryPassageInfons
    | number
    | string
    | PublicationsExportBiocjsonResponseEntryPassageAnnotation
}

export type PublicationsExportBiocjsonResponseEntryPassageAnnotation = {
  id: string
  infons: PublicationsExportBiocjsonResponseEntryPassageAnnotationInfons
  text: string
  locations: Array<PublicationsExportBiocjsonResponseEntryPassageAnnotationLocation>
  [key: string]:
    | unknown
    | string
    | PublicationsExportBiocjsonResponseEntryPassageAnnotationInfons
    | PublicationsExportBiocjsonResponseEntryPassageAnnotationLocation
}

export type PublicationsExportBiocjsonResponseEntryPassageAnnotationInfons = {
  identifier?: string
  type?: string
  valid?: boolean
  normalized?: Array<string>
  database?: string
  normalized_id?: string
  biotype?: PublicationsExportBiocjsonResponseEntryPassageAnnotationInfonsBiotype
  name?: string
  accession?: string
  [key: string]:
    | unknown
    | string
    | boolean
    | PublicationsExportBiocjsonResponseEntryPassageAnnotationInfonsBiotype
}

export type PublicationsExportBiocjsonResponseEntryPassageAnnotationInfonsBiotype =
  | 'cellline'
  | 'chemical'
  | 'disease'
  | 'gene'
  | 'species'
  | 'variant'

export type PublicationsExportBiocjsonResponseEntryPassageAnnotationLocation = {
  offset: number
  length: number
  [key: string]: unknown | number
}

export type PublicationsExportBiocjsonResponseEntryPassageInfons = {
  journal: string
  year: string
  title: string
  authors: string
  [key: string]: unknown | string
}

export type SearchResponse = {
  results: Array<SearchResponseArticle>
  page_size: number
  current: number
  count: number
  total_pages: number
  [key: string]: unknown | SearchResponseArticle | number
}

export type SearchResponseArticle = {
  _id: string
  pmid: number
  title: string
  journal: string
  authors: Array<string>
  [key: string]: unknown | string | number
}

export type SearchData = {
  query: {
    /**
     * Page number for paginated results.
     */
    page?: number
    /**
     * Search term(s) to query PubTator.
     */
    text: string
  }
}

export type SearchResponse2 = SearchResponse

export type SearchError = unknown

export type PublicationsExportBiocjsonData = {
  query: {
    /**
     * Comma-separated list of PubTator article PMIDs.
     */
    pmids: string
  }
}

export type PublicationsExportBiocjsonResponse2 = PublicationsExportBiocjsonResponse

export type PublicationsExportBiocjsonError = unknown
