// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError'
      },
      title: 'Detail',
      type: 'array'
    }
  },
  title: 'HTTPValidationError',
  type: 'object'
} as const

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string'
          },
          {
            type: 'integer'
          }
        ]
      },
      title: 'Location',
      type: 'array'
    },
    msg: {
      title: 'Message',
      type: 'string'
    },
    type: {
      title: 'Error Type',
      type: 'string'
    }
  },
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
  type: 'object'
} as const
