// This file is auto-generated by @hey-api/openapi-ts
import { type Options, createClient, createConfig } from '@hey-api/client-fetch'

import type {
  HandlePredictApiV1PredictGetData,
  HandlePredictApiV1PredictGetError,
  HandlePredictApiV1PredictGetResponse,
  VersionApiV1VersionGetError,
  VersionApiV1VersionGetResponse
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Handle Predict
 * Predict genes for a given set of HPO terms and optionally genes.
 */
export const handlePredictApiV1PredictGet = <ThrowOnError extends boolean = false>(
  options: Options<HandlePredictApiV1PredictGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    HandlePredictApiV1PredictGetResponse,
    HandlePredictApiV1PredictGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/predict'
  })
}

/**
 * Version
 */
export const versionApiV1VersionGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    VersionApiV1VersionGetResponse,
    VersionApiV1VersionGetError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/version'
  })
}
